name: lint

on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.13"
    steps:
    - uses: actions/checkout@v3
    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}-${{ matrix.python-version }}
        restore-keys: |
          ${{ runner.os }}-uv-${{ matrix.python-version }}
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv --python 3.13
        uv pip install .[dev]
      with:
        cache-key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}-${{ matrix.python-version }}
        cache-name: uv
    - name: Analyzing the code with our lint
      run: |
        make lint
