name: lint

on:
  push:
    branches: [ main, james/uv-migration ]
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.13"
    steps:
    - uses: actions/checkout@v3
    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-uv-
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Set up Python ${{ matrix.python-version }}
      run: uv venv --python 3.13
      cache: uv
    - name: Install dependencies
      run: uv pip install -e .[dev]
    - name: Analyzing the code with our lint
      run: |
        make lint
