name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      run: uv venv --python 3.13
      cache: uv
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Install dependencies
      run: uv pip install -e .[dev]
    - name: Build
      run: uv build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      run: uv venv --python 3.13
      cache: uv
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Install dependencies
      run: uv pip install -e .[dev]
    - name: Build
      run: uv build
    - name: Publish to PyPI
      run: |
        uv config repositories.remote https://upload.pypi.org/legacy/
        uv --no-interaction -v publish --build --repository remote --username "__token__" --password "$PYPI_API_TOKEN"
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
